name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test docker image
      run: |
        cd stable/alpine
        echo "[DEBUG] Building..."
        docker build -t nginx-lua:alpine-test .
        echo "[DEBUG] Testing..."
        docker run  --entrypoint nginx nginx-lua:alpine-test -version | tee nginx.version
        if [[ $(cat nginx.version | grep "nginx/1.24.0" | wc -l) -le 0 ]]; then exit 1; fi
